version: '3.7'

services:
  java-image:
    build:
      context: .
    image: java-training:latest
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./:/java
  db:
    image: mysql:8.0.21
    ports:
      - "3306:3306"
    env_file:
      - .env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
        - db:mysql
    ports:
        - 8689:80
    environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: password
        PMA_HOST: mysql