version: '3.7'

services:
  server:
    build:
      context: .
    image: spring-server-training:latest
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
  db:
    image: mysql:8.0.21
    ports:
      - "3306:3306"
    env_file:
      - .env